helios-ag/FMElfinderBundle

README.md
README.md update to explain #108 (cors support) and #109 (multiple upload folders by instance) pull requests
=> CORS and home folder guides

README.md
Changed some information how to setup S3.
=> S3 example configuration and url fix

Configuration/ElFinderConfigurationReader.php
Resolves 5.3 incompatibility, resolves #130
=> array short syntax removed

Configuration/ElFinderConfigurationReader.php, DependencyInjection/Configuration.php
Allow setting the directoryPerm parameter. Related to https://github.com/thephpleague/flysystem/pull/457 and https://github.com/thephpleague/flysystem-sftp/pull/6
=> Allow setting the directoryPerm parameter

Controller/ElFinderController.php
The fail is not related to this change, so everything is OK for merge :) @helios-ag
=> Expose pathPrefix to custom editors

Loader/ElFinderLoader.php
The clean version.
Issue: https://github.com/helios-ag/FMElfinderBundle/issues/169
part 1/2: https://github.com/helios-ag/ElFinderPHP/pull/32
=> encode/decode access from FMElfinderBundle Loader (2/2) 

Resources/views/Elfinder/helper/assets_css.html.twig, Resources/views/Elfinder/helper/assets_js.html.twig
=> Fix paths for elfinder-component 2.0 compatibility 

Resources/doc/events-listeners-subscribers.md
As pointed out [here](https://github.com/helios-ag/ElFinderPHP/issues/37#issuecomment-169344021).
=> events doc precision

Resources/doc/ckeditor-integration.md
=> CKEditor integration doc homeFolder precision

Configuration/ElFinderConfigurationReader.php, Tests/Configuration/ElFinderConfigurationReaderTest.php
Hi,
I've made some unit tests to cover the file URL generation and to assert there are no double slashes in file's URL (solves #161 ).
Do you agree with this expected behaviour ?
=> file URL double slashes removal + unit tests

Configuration/ElFinderConfigurationReader.php, Tests/Configuration/ElFinderConfigurationReaderTest.php
little, but annoying bug, that prevented to use a custom URL for thumbnails.
=> Fix case of tmbURL option

Controller/ElFinderController.php, README.md, composer.json
fixed simple template and improved readme file
=> fixed simple template and improved readme file

Configuration/ElFinderConfigurationReader.php, DependencyInjection/Configuration.php, Loader/ElFinderLoader.php, Resources/doc/flysystem.md, Tests/DependencyInjection/ConfigurationLoadTest.php, Tests/DependencyInjection/FMElfinderExtensionTest.php, Tests/Twig/Extension/FMElfinderExtensionTest.php, composer.json
| Bug fix?      | [no]
| New feature?  | [yes]
| BC breaks?    | [no]
| Deprecations? | [yes]
| Tests pass?   | [yes]
| Fixed tickets | [#224]
=> Flysystem custom adapter

Configuration/ElFinderConfigurationReader.php
=> added aws s3 v3 optional_prefix parameter

README.md
=> add missing documentation

DependencyInjection/Configuration.php
| Bug fix?      | [yes]
| New feature?  | [no]
| BC breaks?    | [no]
| Deprecations? | [no]
| Tests pass?   | [yes]
| Fixed tickets | [262]
=> made archivers node optional

README.md, composer.json
=> Fix Symfony versions

Configuration/ElFinderConfigurationReader.php, Tests/Configuration/ElFinderConfigurationReaderTest.php
=> Consistent urls

Twig/Extension/FMElfinderExtension.php
I simply replace :
FMElfinderBundle:Elfinder/helper:
with :
@FMElfinder/Elfinder/helper/
| BC breaks?    | ??
| Tests pass?   |  ??
| Fixed tickets | https://github.com/helios-ag/FMElfinderBundle/issues/306
=> Compatibility to SF4 in FMElfinderExtension.php

DependencyInjection/Configuration.php, Tests/DependencyInjection/ConfigurationLoadTest.php
| Bug fix?      | [yes]
| New feature?  | [no]
| BC breaks?    | [yes]
| Deprecations? | [no]
| Tests pass?   | [yes]
| Fixed tickets | []
=> Change default /assets path to assets

CHANGELOG.md, README.md
| Bug fix?      | [no]
| New feature?  | [no]
| BC breaks?    | [no]
| Deprecations? | [no]
| Tests pass?   | [yes]
=> Updated Changelog and referenced version 9 of the bundle in Readme

.travis.yml, src/DependencyInjection/Configuration.php
Check against phph 7.3 and Symfony 4.1 and 4.2
=> Travis test

src/Loader/ElFinderLoader.php
=> fixed call to a protected member

src/Configuration/ElFinderConfigurationReader.php, src/DependencyInjection/Configuration.php
(For minio or other s3-agnostic interfaces)
| New feature?  | yes
| Tests pass?   | N/A
| Fixed tickets | none
=> Allow endpoint and path-style endpoint configuration for aws_s3_v3

src/Resources/views/Elfinder/summernote.html.twig
=> PDF fix #372

README.md
=> yml extensions changed to yaml

README.md, docs/elfinder-form-type.md
=> Fix Yaml syntax issue

src/Controller/ElFinderController.php
Pass formTypeId to custom editor to be able to use it in forms.
=> Pass formTypeId to custom editor

src/Command/ElFinderInstallerCommand.php
=> Fix elfinder:install root dir

src/Command/ElFinderInstallerCommand.php
=> Added option to select docroot

src/ElFinder/ElFinder.php
See https://github.com/Studio-42/elFinder/issues/2642
=> Add missing constant

src/Resources/views/Elfinder/elfinder_type.html.twig
Just fixing some typos in the comments
=> Fix typos in elfinder_type.html.twig

tests/Twig/Extension/FMElfinderExtensionTest.php
=> Replaced deprecated calls

composer.json, phpunit.xml.dist, src/Configuration/ElFinderConfigurationReader.php, src/DependencyInjection/Compiler/ElFinderConfigurationPass.php, src/DependencyInjection/Configuration.php, src/FMElfinderBundle.php, src/Form/Type/ElFinderType.php, src/Twig/Extension/FMElfinderExtension.php, tests/Configuration/ElFinderConfigurationReaderTest.php, tests/FMElfinderBundleTest.php, tests/Form/Type/ElFinderTypeTest.php
=> Added symfony 6 to deps

config/elfinder.xml, src/Controller/ElFinderController.php
Fixes https://github.com/helios-ag/FMElfinderBundle/issues/480
=> Respect custom loader

src/Configuration/ElFinderConfigurationReader.php
=> update configuration reader to use v3 of league flysytem

src/Configuration/ElFinderConfigurationReader.php
Aws Adapter class loading is wrong
=> Change load class AwsS3v3Adapter to AwsS3V3Adapter

docs/advanced-configuration.md, docs/flysystem.md
=> Set correct url to Flysystem in advanced-configuration.md

docs/flysystem.md
=> Fix typo in flysystem.md

src/Command/ElFinderInstallerCommand.php, src/Configuration/ElFinderConfigurationProviderInterface.php, src/Controller/ElFinderController.php, src/Event/ElFinderPostExecutionEvent.php
Seems like strict_types =1 cause some issues, reverting this
=> Removed strict and added default value

src/Connector/ElFinderConnector.php
=> Revert exit

src/Configuration/ElFinderConfigurationReader.php
See: https://github.com/helios-ag/FMElfinderBundle/issues/528
=> Fixes #528 set default options to empty array

composer.json
=> Bundles should not have symfony/flex in their dependencies

.gitignore
=> gitignore PHPUnit cache folder

.github/workflows/test.yaml, src/Controller/ElFinderController.php, src/Event/ElFinderPostExecutionEvent.php
I've also added PHP 8.4 to the github workflow
=> Fix PHP 8.4 deprecations
