- Controller/ElFinderController.php
- DependencyInjection/Configuration.php
- README.md
Allow a custom template to renderer Elfinder component.
It's interesting if you use a custom WYSIWYG editor you want to integrate with this bundle.
> Allow custom template renderer

- README.md
Here's how it looks in the [IvoryCKEditorBundle doc](https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/file_browse_upload.md):
```
$builder->add('field', 'ckeditor', array(
'config' => array(
'filebrowserBrowseRoute'           => 'my_route',
'filebrowserBrowseRouteParameters' => array('slug' => 'my-slug'),
'filebrowserBrowseRouteAbsolute'   => true,
),
));
```
> IvoryCKEditor sample was incorrect

- Resources/views/Form/elfinder_widget.html.twig
It will trigger `change` event when new value is set from ElFinder popup. Now this event isn't triggered, and binding of events to `input` aren't work.
> Add triggering of change event

- Controller/ElFinderController.php
When use Elfinder as Form Type I have error: 
Variable "pathPrefix" does not exist in FMElfinderBundle:Elfinder:elfinder_type.html.twig at line 19
> Fix bug "pathPrefix" when use Form Type

- DependencyInjection/Configuration.php
The root parameter for Flysystem/FTP was not defined in Configuration.php. Because of this, in ELFinderConfigurationReader in configureFlysystem method $opt['ftp']['root'] was not defined.
> Fixed configuration loading for root parameter (ftp)

- DependencyInjection/Configuration.php
- Tests/DependencyInjection/ConfigurationLoadTest.php
- Tests/Fixtures/config/config.php
- Tests/Fixtures/config/config.xml
- Tests/Fixtures/config/config.yml
The `attributes` configuration setting to set the permissions of files did not work.
See https://github.com/Studio-42/elFinder/wiki/Simple-file-permissions-control
> Fixed configuration loading of attributes.

- Configuration/ElFinderConfigurationReader.php
- Controller/ElFinderController.php
- DependencyInjection/Configuration.php
- Event/ElFinderEvents.php
- Event/ElFinderPostExecutionEvent.php
- Event/ElFinderPreExecutionEvent.php
- FMElfinderBundle.php
- Loader/ElFinderLoader.php
- README.md
- Tests/DependencyInjection/ConfigurationLoadTest.php
Hi,
This PR provides events on elFinder command execution (pre and post).
It also allows to make subrequests to relaunch an elFinder command.
A new setting has been added : `volume_id`, necessary to keep the volume identifier when making subrequests on the same volume than the main request.
Related to [# 19](https://github.com/helios-ag/ElFinderPHP/pull/19) on the lib side.
> Command execution events + subrequests support + volume_id setting

- .gitignore
- Tests/Controller/ElFinderControllerTest.php
- Tests/Event/ElFinderPostExecutionEventTest.php
- Tests/Event/ElFinderPreExecutionEventTest.php
- Tests/Functional/AppKernel.php
- Tests/Functional/config/config.yml
- Tests/Functional/config/config_test.yml
- Tests/Functional/config/routing.yml
- composer.json
Unit tests for events added in PR #128 :
- Testing the dispatching of pre and post execution events
- Testing the `hasErrors` function of postExecutionEvent
- Testing the `getCommand` and `subRequest` functions of preExecutionEvent
Sorry for not having pushed it earlier, I wasn't very familiar with unit tests :stuck_out_tongue_closed_eyes: 
See you :wink:
> Events unit tests

- Controller/ElFinderController.php
- Loader/ElFinderLoader.php
the 2 new function that i have provide recently can't be used in the onPreExecute Event.
So i had to entirely review the functionnality.
Now it is accessible on both onPreExecute & onPostExecute Event. AND it's much more easy to use.
As you don't have to provide the Request parameter in the method :P 
issue : https://github.com/helios-ag/FMElfinderBundle/issues/174
part 1/2 : https://github.com/helios-ag/ElFinderPHP/pull/33
> Access to the encode/decode function From onPreExecute (2/2)

- Controller/ElFinderController.php
- DependencyInjection/Configuration.php
- README.md
- Resources/views/Elfinder/ckeditor.html.twig
- Resources/views/Elfinder/elfinder_type.html.twig
- Resources/views/Elfinder/fm_tinymce.html.twig
- Resources/views/Elfinder/simple.html.twig
- Resources/views/Elfinder/summernote.html.twig
- Resources/views/Elfinder/tinymce.html.twig
- Resources/views/Elfinder/tinymce4.html.twig
- Tests/DependencyInjection/ConfigurationLoadTest.php
The Elfinder JS plugin has an option called `onlyMimes` that will only show those kinds of files in the file browser. Previously, overriding the Controller and templates was the only way to set this option.
Now, the `visible_mime_types` can be set per Elfinder instance, through the bundle configuration.
You might notice that I convert the `visible_mime_types` variable from a PHP array to a string representation of a JS array, before passing to the templates. This is to keep the templates cleaner.
> Bundle configuration for visible mime types

- Tests/Configuration/ElFinderConfigurationReaderTest.php
Hi,
This fixes the merge of the previous #215 and #216 pull requests. Each of these PR were based on the same commit on the master branch, but in the #215 PR I made some changes in the `ElFinderConfigurationReaderTest.php` file. These changes were incompatible with the new test added in #216 PR.
So here comes the fix (sorry about that by the way...).
> tmbURL unit test merge fix

- Resources/views/Form/elfinder_widget.html.twig
jQuery is included at the end of my page, and thus is not ready when the form element is rendered.
DOMContentLoaded is compatible with all web browsers except IE8 (http://caniuse.com/#feat=domcontentloaded).
> wrap jQuery around DOMContentLoaded

- .travis.yml
- Controller/ElFinderController.php
- DependencyInjection/Compiler/TwigFormPass.php
- DependencyInjection/Configuration.php
- DependencyInjection/FMElfinderExtension.php
- Resources/views/Elfinder/ckeditor.html.twig
- Resources/views/Elfinder/elfinder_type.html.twig
- Resources/views/Elfinder/fm_tinymce.html.twig
- Resources/views/Elfinder/simple.html.twig
- Resources/views/Elfinder/summernote.html.twig
- Resources/views/Elfinder/tinymce.html.twig
- Resources/views/Elfinder/tinymce4.html.twig
- Tests/DependencyInjection/Compiler/TwigFormPassTest.php
- Twig/Extension/FMElfinderExtension.php
- composer.json
Corrected template paths for twig extension in SF4.
Also, I think you should fix the "assets_path" in the default configuration because in SF4 assets are placed in the public folder by default, but that is your decision. :)
> Fixed twig extension for SF4.

- DependencyInjection/Configuration.php
| Tests pass?   | yes/no
I upgraded to the latest v.8.0 version I faced to an issue with the new encoding parameter. When no value is provided, a 500 error is triggered with the message `Notice: Undefined index: encoding`
I just propose to change the default value to utf-8.
> Fix default encoding parameter value

- src/Resources/config/routing.yml
Because the bundle notation has been deprecated in sf4.1 ( https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation), namespace notation must be used.
Warning message (symfony profiler and running test):
User Deprecated: Referencing controllers with FMElfinderBundle:ElFinder:load is deprecated since Symfony 4.1, use "FM\ElfinderBundle\Controller\ElFinderController::loadAction" instead.
User Deprecated: Referencing controllers with FMElfinderBundle:ElFinder:show is deprecated since Symfony 4.1, use "FM\ElfinderBundle\Controller\ElFinderController::showAction" instead.
| BC breaks?    | yes
| Deprecations? | yes
> New way to referencing controller

- src/Controller/ElFinderController.php
Current behaviour is a PHP warning as url input is not correctly checkec, which results in an error page during development, but a white 200 OK response on production.
When catching this early with a `NotFoundException`, it is clear that the instance does not exist. 
This change adds two major improvements:
- During development there will be a Symfony error page with a "Instance not found" instead of a "Notice: Undefined index: ".
- The user on production will be presented with an accurate 404 not found page, which can be customized by the application (instead of a 200 OK page with some random content, but white result).
| New feature?  | yes
| …
> Throw not found exception on unknown instance

- src/Connector/ElFinderConnector.php
In standart elfinder connector there is `exit` in `output` method (dump).
https://github.com/Studio-42/elFinder/blob/b3a6555758656379c67e981a386c2fbc72507910/php/elFinderConnector.class.php#L290
echo and exit... Are you kidding ? 😄 
More description:
We will never be here 
https://github.com/helios-ag/FMElfinderBundle/blob/184dc241cb8473060218084d054d71ce1a9beacc/src/Controller/ElFinderController.php#L233
> Post execution event fix

- README.md
- src/Configuration/ElFinderConfigurationReader.php
- tests/Configuration/ElFinderConfigurationReaderTest.php
| New feature?  | yes
I needed to pass a `homeFolder` from the form type with currently logged in user, so it can modify it's own files. `homeFolder` was not added when url was not absolute.
Now you can use `{homeFolder}` as a placeholder in url and it will be replaced automatically.
> Add homeFolder to url

- src/Twig/Extension/FMElfinderExtension.php
- tests/Twig/Extension/FMElfinderExtensionTest.php
It is as simple as replacing Twig_* classes with actual classes that are supported and available in all twig versions. Also updated test to reflect those changes.
> Update twig extension to use supported Twig classes instead of legacy ones

- src/Controller/ElFinderController.php
The MIME type of the javascript should be `text/javascript`
With the `X-Content-Type-Option` sets to `nosniff`, the finder doesn't even load else
> Setting MIME reply to text/javascript for mainJS

- src/Resources/views/Elfinder/helper/main.js.twig
Hi,
If the website is not deployed under `/`, the bundle actualy doesn't work because of the `baseUrl` present in the `elfinder.main.js` that specifies `/bundles...`, using the `asset()` function fixes this issue.
> Using asset() to ensure the URL is correct (if website not deployed under /)

- src/Configuration/ElFinderConfigurationReader.php
Rewrite the flow for the instantiation of a filesystem usinga custom adapter
in such a way that it is possible to include a custom driver.
As well as fixing a notice: undefined variable by declaring `$filesystem = null;`
As well as throwing an exception when a custom adapter was unable to instantiate an instance of `Filesystem`
> Improved error message for custom adapter service.

- src/Twig/Extension/FMElfinderExtension.php
There was double elfinder_tinymce_init4 definition which made it impossible to load tinymce4 resource.
> Fix elfinder_tinymce_init4 duplicate definition

- src/Configuration/ElFinderConfigurationReader.php
I've noticed that the plugin options aren't correctly passed.
The function $volume->getOptionsPlugin(...) always returns an empty array.
This PR should fix it.
Affected versions: from 9.3 upwards for sure
> fix plugin options not passed

- src/Command/ElFinderInstallerCommand.php
> User Deprecated: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "FM\ElfinderBundle\Command\ElFinderInstallerCommand" class instead.
> Fix symfony 6.1 deprecation

- .github/workflows/test.yaml
- src/Configuration/ElFinderConfigurationReader.php
The S3 Client, from the official AWS SDK, allows instantiating itself without having the credentials specified (this way the credential provider will try to resolve the credentials from environment variables, or try to authenticate - at runtime - the instance based on its profile id).
This PR enables this behavior, for those who wants to use it.
Thank you.
> Allow no-credentials for S3 Client

- src/Controller/ElFinderController.php
- src/Resources/views/Elfinder/helper/main.js.twig
Fix for the issue: **Failed to load ressources with framework.assets.version** #429 
I just added the EmptyVersionStrategy so don't break the RequireJs
> Remove framework assets version to be able to work with RequireJs.

- src/Controller/ElFinderController.php
Following issue #491, in **ElFinderController**, when defining **$mainUrl** at line 229, this is a relative path and not absolute.
To make it absolute, a **/** have been added according to the [Symfony documentation](https://symfony.com/doc/current/components/asset.html#usage).
> Fixes #491 - mainUrl was not an absolute path

- src/Connector/ElFinderConnector.php
This exit is unnecessarily exiting PHP entirely. Why is this even here?
> Fix unnecessary PHP exit

- src/Command/ElFinderInstallerCommand.php
When the `vendor` folder is not in the `%kernel.project_dir%`, the `elfinder:install` command fails:
```
./bin/console elfinder:install
elFinder Installer
==================
// Trying to install elfinder to public directory
! [NOTE] Starting to install elfinder to /var/www/html/docroot/public/bundles/fmelfinder folder
In Filesystem.php line 544:
The origin directory specified "/var/www/html/docroot/vendor/studio-42/elfinder/css" was not found.
```
This is typically the case when the `vendor` folder is outside of the webroot dir, which is from security point of view a best practice.
This PR ensures the `vendor` folder location is determined based on the composer classloader.
This both works for application with the `vendor` inside and outside the webroot dir.
> determine the vendor root dir based on the composer classloader

- src/Connector/ElFinderConnector.php
- src/Loader/ElFinderLoader.php
This should correctly remove the exit, and return the correct response.
> Correctly fix return of Connector and Loader in non-cors mode

- docs/flysystem.md
I think some extra information about setting endpoint without bucket subdomain is quite useful. I really struggled to find this configuration to setup aws localstack for local env.
> Flysystem.md add extra info about endpoint with use_path_style_endpoint

- src/FMElfinderBundle.php
Fixes this warning:
User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "FM\ElfinderBundle\FMElfinderBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
> Add return type to FMElfinderBundle::build()

- src/DependencyInjection/Compiler/TwigFormPass.php
This fixes the warning:
Method
"Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface::process()" might add "void" as a native return type declaration in the future. Do the same in implementation
"FM\ElfinderBundle\DependencyInjection\Compiler\TwigFormPass" now to avoid errors or add an explicit @return annotation to suppress this message.
> Add return type to TwigFormPass::process()

- src/Form/Type/ElFinderType.php
This fixes the below warnings:
Method
"Symfony\Component\Form\AbstractType::buildForm()" might add "void" as a native return type declaration in the future. Do the same in child class
"FM\ElfinderBundle\Form\Type\ElFinderType"
now to avoid errors or add an explicit @return annotation to suppress this message.
Method
"Symfony\Component\Form\AbstractType::buildView()" might add "void" as a native return type declaration in the future. Do the same in child class
"FM\ElfinderBundle\Form\Type\ElFinderType"
now to avoid errors or add an explicit @return annotation to suppress this message.
Method
"Symfony\Component\Form\AbstractType::configureOptions()" might add "void" as a native return type declaration in the future. Do the same in child class
"FM\ElfinderBundle\Form\Type\ElFinderType"
now …
> Add return types to ElFinderType

- docs/configuration-dump.md
- docs/flysystem.md
- src/Configuration/ElFinderConfigurationReader.php
- src/DependencyInjection/Configuration.php
Allow option configuration for S3Client : use_aws_shared_config_files
It prevent AWS PHP SDK to check presence of shared configuration file in folder that may be protected (creating an error in path secured environment)
> Add use_aws_shared_config_files option to fm_elfinder configuration

- src/Controller/ElFinderController.php
Add missing asset path for main_url to correctly load the assets.
Fixes #497
> Fixes #497 mainUrl didn't contain asset path

- src/ElFinder/ElFinder.php
Fixes issue [!531](https://github.com/helios-ag/FMElfinderBundle/issues/531)
Proposed by [dleffler](https://github.com/dleffler) in [Studio-42/elFinder](https://github.com/Studio-42/elFinder/issues/3546)
> Fix : Use of "self" in callables is deprecated

- src/ElFinder/ElFinder.php
- src/Twig/Extension/FMElfinderExtension.php
- tests/bootstrap.php
> Use modern first class callable syntax

- src/Loader/ElFinderLoader.php
Fix "Typed property FM\ElfinderBundle\Loader\ElFinderLoader::$session must not be accessed before initialization" caused by FMElfinderBundle/src/Loader/ElFinderLoader.php:65
> Fix Typed property must not be accessed before initialization
